#theme: jekyll-theme-minimal
#title: Absent Service's Github Page
#description: Bookmark this to keep an eye on my project updates!

title: AbsentPlay's Page
#tagline: tagline
description: Just Take a Peak
show_downloads: true #["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: 
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
